project:
  type: website
  output-dir: docs

website:
  title: "Colin Hassett"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    page-layout: full

editor: visual
execute:
  freeze: auto
